repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.20.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        args:
          [
            --config,
            eslint.config.mjs,
            "lib/**/*.ts",
            "constructs/**/*.ts",
            "bin/**/*.ts",
            --fix,
          ]
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        args: [--write]
        exclude: |
          (?x)(
              ^.github/|
              ^.projen/|
              ^.mergify.yml|
              ^.*.json |
              ^TF_DOCS.md 
          )
  - repo: local
    hooks:
      - id: terraform-validate
        name: terraform validate
        entry: .pre-commit/hooks/terraform-validate.sh
        language: system
  - repo: local
    hooks:
      - id: terraform-docs
        name: Generate Combined Terraform Docs
        entry: .pre-commit/hooks/terraform-docs.sh
        language: script
        pass_filenames: false
        always_run: true
